# Generated by Django 6.0.5 on 2026-05-15 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(help_text='Ej. Metros, Unidades, Kg', max_length=20)),
                ('stock_bodega', models.IntegerField(default=0)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_BODEGA', 'Ingreso a Bodega (Compra/Proveedor)'), ('SALIDA_PROYECTO', 'Salida a Proyecto'), ('DEVOLUCION_PROYECTO', 'Devolución de Proyecto a Bodega')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
                ('usuario_registra', models.ForeignKey(help_text='Supervisor o Bodeguero que hace el movimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, help_text='Obligatorio si es salida o devolución', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proyecto')),
            ],
        ),
    ]
