# Generated by Django 6.0.5 on 2026-05-15 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_serie', models.CharField(help_text='Código único o número de serie', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('BUENO', 'Buen Estado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DEBAJA', 'Dada de Baja / Dañada')], default='BUENO', max_length=20)),
                ('en_bodega', models.BooleanField(default=True)),
                ('proyecto_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proyecto')),
                ('tecnico_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aceptación'), ('ACEPTADO', 'Aceptado (Traspaso Exitoso)'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.herramienta')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto al que va la herramienta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proyecto')),
                ('tecnico_destino', models.ForeignKey(help_text='Quién recibe', on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('tecnico_origen', models.ForeignKey(help_text='Quién entrega', on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
