# Generated by Django 6.0.5 on 2026-05-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horas_extras_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horas_totales_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
