# Generated by Django 6.0.5 on 2026-05-16 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_asistencia_horas_extras_dia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientomaterial',
            old_name='fecha',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='movimientomaterial',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='movimientomaterial',
            name='usuario_registra',
        ),
        migrations.AddField(
            model_name='movimientomaterial',
            name='estado_checklist',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente por revisar por el Técnico'), ('ACEPTADO', 'Aceptado por el Técnico (Checklist OK)'), ('RECHAZADO', 'Rechazado / Con Novedad')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='movimientomaterial',
            name='notas_novedad',
            field=models.TextField(blank=True, help_text='Notas en caso de que falte algo o llegue dañado', null=True),
        ),
        migrations.AddField(
            model_name='movimientomaterial',
            name='tecnico_receptor',
            field=models.ForeignKey(blank=True, help_text='Técnico que recibe el material en obra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientomaterial',
            name='usuario_bodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_despachados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientomaterial',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientomaterial',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_BODEGA', 'Ingreso a Bodega (Compra/Proveedor)'), ('SALIDA_PROYECTO', 'Salida a Proyecto (Obra)'), ('DEVOLUCION_PROYECTO', 'Devolución desde Proyecto')], max_length=20),
        ),
    ]
