# Generated by Django 6.0.5 on 2026-05-17 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_fecha_movimientomaterial_fecha_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(help_text='Ej: Instalación de paneles, Conexión AC, etc.', max_length=100)),
                ('porcentaje_avance', models.IntegerField(default=0, help_text='Progreso de 0 a 100')),
                ('notas_progreso', models.TextField(blank=True, help_text='¿Qué falta o por qué se pausó?', null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='inventario.proyecto')),
            ],
        ),
    ]
