# Generated by Django 6.0.5 on 2026-05-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_etapaproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomaterial',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Nombre del proveedor externo (Opcional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientomaterial',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.proyecto'),
        ),
        migrations.AlterField(
            model_name='movimientomaterial',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_BODEGA', 'Ingreso a Bodega (Abastecimiento)'), ('SALIDA_PROYECTO', 'Salida a Proyecto (Obra)'), ('DEVOLUCION_PROYECTO', 'Devolución desde Proyecto'), ('COMPRA_DIRECTA', 'Compra Directa a Obra (No pasa por bodega)')], max_length=20),
        ),
    ]
