# Generated by Django 6.0.5 on 2026-05-27 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimientomaterial_proveedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCompraDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(help_text='Nombre escrito a mano en la app', max_length=150)),
                ('cantidad', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_directas', to='inventario.proyecto')),
                ('usuario_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_directas_despachadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
