# Generated by Django 6.0.5 on 2026-06-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_materialcompradirecta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAvanceDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('porcentaje_al_momento', models.IntegerField(help_text='Porcentaje guardado en este día')),
                ('nota_labor', models.TextField(help_text='Descripción de la labor del día')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='evidencias/fotos/%Y/%m/%d/')),
                ('video_evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/videos/%Y/%m/%d/')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_diarios', to='inventario.etapaproyecto')),
                ('usuario', models.ForeignKey(help_text='Técnico que reporta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
