# Generated by Django 6.0.5 on 2026-06-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_reporteavancediario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEvidenciaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evidencias/fotos/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionales', to='inventario.reporteavancediario')),
            ],
            options={
                'verbose_name': 'Foto de Evidencia',
                'verbose_name_plural': 'Fotos de Evidencias',
                'ordering': ['id'],
            },
        ),
    ]
